# Generated by Django 4.0.6 on 2022-07-25 07:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='وضعیت نویسنده بودن'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 7, 41, 39, 983866, tzinfo=utc), verbose_name='وضعیت اشتراک ویژه'),
        ),
    ]
