# Generated by Django 4.0.6 on 2022-07-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='descriptions',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='آدرس مقاله'),
        ),
    ]
