# Generated by Django 4.0.6 on 2022-07-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_descriptions_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='مقاله ویژه  '),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده '), ('i', 'در حال بررسی'), ('b', 'برگشت داده شده')], max_length=10, verbose_name='وضعیت انتشار'),
        ),
    ]
